# Generated by Django 4.1.7 on 2023-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('location', models.CharField(max_length=1000, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('humidity', models.FloatField(verbose_name='humidity')),
                ('heatIndex', models.FloatField(verbose_name='heatIndex')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.sensor')),
            ],
        ),
    ]
